blog/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views


urlpatterns = [
    path('', views.index,name='index'),
    path('article/<int:pk>', views.article, name='get_article'),
    path('author/<int:pk>', views.author, name='author'),
    path('create', views.create, name='create'),
    path('article',views.article1,name='article')
]

main/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField(max_length=256)
    
    def __str__(self): return self.name
    
class Article(models.Model):
    title = models.CharField(max_length=256)
    content = models.TextField()
    file = models.FileField(null = True,blank = True)
    createdAt = models.DateTimeField(auto_now_add=True)
    
    authors = models.ManyToManyField('Author')

    def __str__(self):
        return self.title

main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from main import models

# Create your views here.
def index(request):
    latest_article = models.Article.objects.all().order_by('-createdAt')[:10]
    context = {
        'latest_article': latest_article
    }
    return render(request, 'main/index.html', context)
    
def article(request,pk):
    article= get_object_or_404(models.Article,pk=pk)
    context = {
        'article':article
    }
    return render(request, 'main/article.html', context)

def article1(request):
    article= get_object_or_404(models.Article)
    context = {
        'article':article
    }
    return render(request, 'main/article.html', context)

def author(request, pk):
    author = get_object_or_404(models.Author,pk=pk)
    context = {
        'author': author
    }
    return render(request, 'main/author.html', context)

def create(request):
    authors = models.Author.objects.all()
    context = {
        'authors': authors
    }
    if request.method == "POST":
        article_data = {
            "title": request.POST['title'],
            "content": request.POST['content'],
            "file":request.POST['file']
        }
        article = models.Article.objects.create(**article_data)
        author = models.Author.objects.filter(pk=request.POST['author'])
        article.authors.set(author)
        context["sucess"] = True
    return render(request,'main/create.html',context)

templates/main/article.html
{% extends 'main/base.html' %}
{% block content %}
 {% include 'main/navbar.html' %}
  <div class="container">
      <h4 class="center-align">{{ article.title }}</h4>
        
        <h6 class="right-align">Created at : {{ article.createdAt }}</h6>
        <h6>Written By:
           
                {% for author in article.authors.all%} 
               
                   <a href="{% url 'author' author.id %}">{{ author }}</a>
               
            {% endfor %}
            
               
        </h6>
        <div class="row">
            <p>
                {{ article.content }}
            </p>
        </div>
      
  </div>
{% endblock %}

templates/main/author.html
{% extends 'main/base.html' %}
{% block content %}
 {% include 'main/navbar.html' %}
  <div class="container">
      <div class="row">
          <h5>Name : {{ author.name }}</h5>
           <h6>Aritcle written by</h6>
           {% for article in author.article_set.all %}
           <li>
            <a href="{% url 'get_article' article.id %}">{{ article.title }}</a>

           </li>
             

           {% endfor %}

      </div>
      
  </div>
{% endblock %}

templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

     <!-- Compiled and minified CSS -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

     <!-- Compiled and minified JavaScript -->
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
     <title>Blog</title>
     <link rel = "icon" href =  "{{ 'media/blog.png '}}" type = "image/x-icon"> 
             
</head>
<body>
    {% block content %} {% endblock %}
    {% block script %} {% endblock %}
</body>
</html>

templates/main/create.html
{% extends 'main/base.html' %}
{% block content %}
 {% include 'main/navbar.html' %}
  <div class="container">
    <div class="row">
        <div class="col s12">
          <div class="row">
            <h5 class="center-align" style="font:bold;">Share your valuable Thoughts❤️</h5>
            <div class="input-field col s12">
                <form method="post">
                    {% csrf_token %}
                    <input type="text",name="title" placeholder="Title">
                    <textarea class="materialize-textarea2" name="content" placeholder="Express your Thoughts"></textarea>
                    <select name="author">
                      {% for author in authors %}
                       <option value="{{ author.id }}">{{ author.name }}</option>
                     {% endfor %}
                    </select>
                    
                    <div class="file-field input-field">
                        <div class="btn">
                          <span class="right-align">File</span>
                          <input type="file" multiple>
                        </div>
                        <div class="file-path-wrapper">
                          <input name ='File'class="file-path validate" type="text" placeholder="Upload one or more files">
                        </div>
                    </div>
                    

                    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                    <i class="material-icons right">save</i>
                    </button>
                    <button class="btn waves-effect waves-light" type="reset" name="action">Reset
                    <i class="material-icons right">replay</i>
                    </button>
                        
                </form>
             

            </div>
          </div>
        </div>
      </div>
      
  </div>
{% endblock %}

{% block script %}
<script>
      document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.autocomplete');
    var instances = M.Autocomplete.init(elems);
  });
</script>
{% endblock %}

templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}
 {% include 'main/navbar.html' %}
  <div class="container">
        <h3 class="center-align" style="color:black;">Latest Articles</h3>
      <ul class="collection">
          {% for article in latest_article %}
             <li class="collection-item avatar">
                <img src="media/fairytale.png" alt="" class="circle">
                <span class="title" style="font-size:25px; color: black;">
                  <a href="{% url 'get_article' article.id %}">{{article}}</a>
                </span>
            </li>
          {% endfor %}
      </ul>
  </div>
{% endblock %}

{% block script %}
 <script>
     alert("Welcome to Blog 😃" )
 </script>
{% endblock %}

templates/main/navbar.html
<nav>
    <div class="nav-wrapper">
      <a href="{% url 'index' %}" class="brand-logo">Blogs</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        
        <li><a href="{% url 'article' %}">Explore😃</a></li>
        <li><a href="{% url 'create' %}">Create Article</a></li>
       
      </ul>
    </div>
  </nav>
        